# blocklist
branches:
  except:
    - gh-pages # rely on tags

services:
  - docker

env:
  - DOCKER_TAG=:$TRAVIS_BRANCH

before_install:
  - echo "$DOCKER_TAG"
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
       unset DOCKER_TAG;
    fi

script:
  - docker build -t $DOCKER_USERNAME/ngattuso$DOCKER_TAG .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/ngattuso$DOCKER_TAG
