# blocklist
branches:
  except:
    - gh-pages # rely on tags

services:
  - docker

env
  - DOCKER_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER

before_install:
  - if: branch = master \
      set DOCKER_TAG "latest"

script:
  - docker build -t $DOCKER_USERNAME/ngattuso:$DOCKER_TAG .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/ngattuso:$DOCKER_TAG
